name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # 🔥 STEP 1: Build Docker image
    - name: Build Docker image
      run: docker build -t efrozkhan6194/myapp:v1 .

    # 🔥 STEP 2: Login to DockerHub
    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

    # 🔥 STEP 3: Push image to DockerHub
    - name: Push Docker image
      run: docker push efrozkhan6194/myapp:v1

    # 🔥 STEP 4: Deploy to EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ec2-user
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          sudo docker pull efrozkhan6194/myapp:v1
          sudo docker stop myapp || true
          sudo docker rm myapp || true
          sudo docker run -d -p 80:80 --name myapp efrozkhan6194/myapp:v1
